### ISSUE TITLE
Deprecated Code in "OSM Map Elementor"

### ISSUE THREAD

**Issue by susanhope** [flopperj/osm-map-elementor#30]
Hello,

This is Susan from Elementor. We need a way to contact you regarding the above, please can you supply an email address where we can send the request and assistance, thank you so much.

**Comment by QuoterMusic** [comment]
Hi Susan,

Thanks for your message.

my email for this kind of stuff is: 
dev@niklas-meyer.net

I had fully forgotten about the Elementor Deprecations due to my thesis etc.

I'll do it the next days and adapt the code accordingly. I had already implemented a part of it in an earlier update.

Best regards
Niklas / Quoter

**Comment by QuoterMusic** [comment]
@susanhope 
I have done an update which will soon be online at wordpress.org in which all the deprecated code I could find has been fixed.
If I missed something I would appreciate feedback.

**Comment by rami-elementor** [comment]
@QuoterMusic One more deprecated method - https://github.com/flopperj/osm-map-elementor/pull/35

**Comment by susanhope** [comment]
> Hi Susan,
> 
> Thanks for your message.
> 
> my email for this kind of stuff is: [dev@niklas-meyer.net](mailto:dev@niklas-meyer.net)
> 
> I had fully forgotten about the Elementor Deprecations due to my thesis etc.
> 
> I'll do it the next days and adapt the code accordingly. I had already implemented a part of it in an earlier update.
> 
> Best regards Niklas / Quoter

Thank you so much Niklas, I have made a note of your email address and we will contact you that way if needed.
